<a href="https://colab.research.google.com/github/smaldonado2004/labo_de_datos/blob/main/clase01_guia_de_ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a) Ingresar los siguientes comandos en una sola celda y observar el resultado al apretar
SHIFT-ENTER. ¿Que sucede? ¿Por que?

In [ ]:
2 + 2
3 * 5 #solo hace el ultimo calculo

15

In [ ]:
print (2 + 2)
print (3 * 5) #se ordena hacer ambos calculos

4
15


(c) Orden de ejecucion. Ejecutar el contenido de esta celda dos veces. Cambia la salida?


In [ ]:
a = 5
a = a + 1
print ( a ) #no pq defino a = 5

6


Luego de ejecutar la celda anterior, ejecutar el contenido de esta celda dos veces. ¿Cambia
la salida en cada caso? ¿Por que?

In [ ]:
a = a + 1
print ( a ) #primero sale 7 y luego 8 pq a no tiene un punto de partida fijo

8


4. Antes de probar en la consola, piense que van a dar estas operaciones.

In [ ]:
a , b , c = 3 , 4 , 2
#OJO: esta forma de asignar dice a= 3, b=4 y c=2
print("op1: ", a > b)
print("op2: ",a <= b)
print("op3: ",a != b)
print("op4: ",a == b)
print("op5: ",not( a > b ) )
print("op6: ", (( c > a ) or (10 * c > b ) ) and not ( b / a > c ) )
                # F or ( 10*2 = 20 > 4 TRUE) and not (False)
                # (F or T) and T   ==> T and T

op1:  False
op2:  True
op3:  True
op4:  False
op5:  True
op6:  True


6. **Listas.** Las listas permiten guardar **valores de distintos tipos** en forma ordenada y **acceder a
los distintos elementos por su ındice**, comenzando desde 0.

In [ ]:
s = [1 , 2 , 3.0 , " hola ", 7 + 3]
s , s [0] , s [1] , s [ -1]

([1, 2, 3.0, ' hola ', 10], 1, 2, 10)

7. **Vectores.** Para trabajar con vectores en Python (y en general para todo tipo de operaciones
matematicas) vamos a usar la bibliotece numpy. Para eso importamos primero numpy y definimos
vectores con el comando np.array. Ejecutar el siguiente codigo y observar los resultados.

In [1]:
import numpy as np
v = np . array ([1 ,2 ,3])
w = np . array ([1.2 , 7 , np . pi ])
v , w , v + w

(array([1, 2, 3]),
 array([1.2       , 7.        , 3.14159265]),
 array([2.2       , 9.        , 6.14159265]))

8. La magia de Numpy La biblioteca Numpy reproduce muchas funcionalidades de Matlab. La
mayor´ıa de las operaciones con vectores de Numpy se hacen coordenada a coordenada. Esto
permite en muchos casos evitar usar ciclos o ciclos anidados y realizarlos con un solo comando.
Ejecutar los siguientes comandos e interpretar los resultados.

In [ ]:
np . set_printoptions ( precision =2 , suppress = True )
#La anterior linea no es necesaria para q el codigo funcine, solo se usa para mejorar como se muestran los nros.
  #Precision = 2: muestra solo 2 decimales
  #supress = True: evita notacion cientifica (por ejemplo 1e-05)
v = np . array ([1 ,2 , np .e ,7])
w = np . array ([1.2 , np . pi , 4 , 5])
print ("v+w = ", v + w )
print ("v*w = ", v * w )

v+w =  [ 2.2   5.14  6.72 12.  ]
v*w =  [ 1.2   6.28 10.87 35.  ]


Podemos probar varios comandos en un ciclo

In [ ]:
#Para cada expresion en la lista:
for expr in ["v", "w", "v + w", "v ** 2", "v % 2", "np.sum(v)", "np. sqrt (w)", "v > 3", "w < 3.5 "
]:
  print ( f"{ expr :11s} == { eval ( expr )}")
  #{expr:11s}: expr: la expresion, 11: ocupa 11 espacios, s: string (sirve para alinear la salida a lo q esta antes de ==)
  #eval ( expr ): evalua cada expresion convirtiendola de text. a un res de una op real

v           == [1.   2.   2.72 7.  ]
w           == [1.2  3.14 4.   5.  ]
v + w       == [ 2.2   5.14  6.72 12.  ]
v ** 2      == [ 1.    4.    7.39 49.  ]
v % 2       == [1.   0.   0.72 1.  ]
np.sum(v)   == 12.718281828459045
np. sqrt (w) == [1.1  1.77 2.   2.24]
v > 3       == [False False False  True]
w < 3.5     == [ True  True False False]


9. Bonus: descrifrar que hace la f-string que recibe como argumento print.
  Es una forma de meter variables dentro de un string:

In [ ]:
x = 5
print(f"valor: {x}")

valor: 5



10. Las operaciones logicas or y and no se pueden aplicar a vectores. Debemos usar los sımbolos |
(or) y & (and).

In [3]:
( v > 3) & ( w < 3.5)

array([False, False, False])

11. ¿Como se puede aplicar not a un vector de variables booleanas (x ∈ {True, False})? Pueden
probar algunas ideas o buscar la respuesta en Internet.

In [4]:
vector = np.array([True, False])
~vector #usando ~

array([False,  True])


12. Algunos comandos pueden dar resultados inesperados. Intenten adivinar cual va a ser el resultado de cada comando.

In [7]:
v = np . array ([1 ,2 , np .e ,7])
w = np . array ([1.2 , np . pi , 4 , 5])
z = np . array ([0 ,1])
print(v * w)
print(v +2)

[ 1.2         6.28318531 10.87312731 35.        ]
[3.         4.         4.71828183 9.        ]


In [8]:
v + z # Funcionara ? NO RECORDEMOS QUE PARA LA SUMA TIENE QUE TENER = DIMENSIONES

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

13. Explorar estas distintas formas de extraer informacion de un vector.

In [10]:
v = np . array ([1 , 2 , np .e , 7 , 5])
print("1:", v [0] , v [1] , v [ -1], v[-2])
print("2:",v [[0 , 3]])
print("3:",v [0:3] , v [0:1])

1: 1.0 2.0 5.0 7.0
2: [1. 7.]
3: [1.         2.         2.71828183] [1.]


14. Tambien podemos seleccionar los elementos que cumplan alguna propiedad.

In [11]:
v = np . array ([1 , 2 , np .e , 7 , 5])
w = np . array ([1 , 0 , 2 , 5 , 0])
print(v [ v > 2])
print("devuelve v q cumplen w", v [ w != 0])

[2.71828183 7.         5.        ]
devuelve v q cumplen w [1.         2.71828183 7.        ]


15. **Matrices** Las matrices se definen en numpy como arrays de filas. Las operaciones usuales
se realizan coordenada a coordenada al igual que con vectores. Verificar los resultados de los
siguientes comandos.

In [13]:
A = np . array ([[3 , 2 , 2] , [ -1 , 0 , 1] , [ -2 , 2 , 4]])
B = np . array ([[1 , 0 , 0] , [0 , 1 , 0] , [0 , 0 , 1]])
C = np . array ([[0 , 1 , -1] , [5 , -2 , 1]])
print (A + B)
print (A * B)
print (C **2)
# bonus : pruebe con np
print("usando np", np.square(C))

[[ 4  2  2]
 [-1  1  1]
 [-2  2  5]]
[[3 0 0]
 [0 0 0]
 [0 0 4]]
[[ 0  1  1]
 [25  4  1]]
usando np [[ 0  1  1]
 [25  4  1]]


**Funciones**

Las funciones son bloques de codigo organizado que se usan para realizar tares especıficas.
Reciben un input (un numero o una variable, por ejemplo) y devuelven un output.

Los inputs van
entre parentesis y separados por una coma, si hay mas de uno.

Muchas funciones estan disponibles
en la biblioteca estandar de Python, otras estas agrupadas en distintas bibliotecas, como numpy que
agrupa una gran cantidad de funciones matematicas. El objetivo de estos ejercicios es familiarizarse
con varias funciones basicas de Python.

17. Ejecutar estas operaciones para entender que hacen las funciones de numpy:

In [14]:
a = np . sqrt (2)
a #raiz de 2

np.float64(1.4142135623730951)

In [15]:
np . round ( a ) #redondea al entero mas cercano

np.float64(1.0)

In [16]:
np . round (a , 2) #dos decimales

np.float64(1.41)

18. Muchas funciones de numpy se pueden aplicar tambien en arrays:

In [18]:
v = np . array ([ a , a **2 , a **3 , a **(.5) ])
np . floor ( v ) #redondea al menor entero

array([1., 2., 2., 1.])

19. Explorar las funciones np.max(), np.min(), np.sum(), np.mean() y np.sort() aplicadas al vector
v del ejercicio anterior. ¿Que hace cada una?

In [21]:
v

array([1.41421356, 2.        , 2.82842712, 1.18920712])

In [24]:
print(np.max(v))
print(np.min(v))
print(np.sum(v)) #suma todo el array
print(np.mean(v)) #saca la media
print(np.sort(v)) #ordena de menor a mayor

2.8284271247461907
1.189207115002721
7.431847802122007
1.8579619505305018
[1.18920712 1.41421356 2.         2.82842712]


20. Definir los siguientes vectores como arrays de numpy:
alturas cm = (180, 178, 154, 202),
frutas = (”banana”, ”pera”, ”durazno”).
¿Cuales funciones del ejercicio anterior se pueden aplicar a cada uno de estos vectores? Verifiquen su respuesta.

In [26]:
cm = np.array([180,178,154,202])
frutas = np.array(["banana", "pera", "durazno"])

In [29]:
print(np.max(cm)) #PARA cm TODOS pq son valores igual que antes
print(np.min(cm))
print(np.sum(cm))
print(np.mean(cm))
print(np.sort(cm))

202
154
714
178.5
[154 178 180 202]


In [39]:
#print(np.max(frutas))
#print(np.min(frutas))
#print(np.sum(frutas))
#print(np.mean(frutas))
print(np.sort(frutas)) #SOLO PUEDE ORDENAR EN ORDEN ALFABETICO

['banana' 'durazno' 'pera']


21. Utilizando solo las operaciones y funciones vistas en los ejercicios anteriores, escribir códigos de una sola línea para las siguientes funciones matemáticas.

(a) $\|v\|_2 = \sqrt{v_1^2 + v_2^2 + \dots + v_n^2} = \sqrt{\sum_{i=1}^{n} v_i^2}$

In [46]:
#ITEM A
np.sqrt(np.sum(np.square(v)))

np.float64(3.926093931934525)

22. En Python podemos definir nuestras propias funciones utilizando def. ¿Que hace la siguiente
funcion? ¿Que resultados esperan al aplicar la funcion a los vectores v0 y v1?

In [52]:
def todosPositivos ( v ) :
  return np .all ( v > 0) #True si todo V cumple eso
v0 = np . array ([3 , 4])
v1 = np . array ([3 , 5 , -1 , 1])

print(todosPositivos(v0))  # True
print(todosPositivos(v1))  # False

True
False


24. Usar las funciones np.argmin() y np.argmax() con el vector de alturas definido anteriormente.
Interpretar que hace cada una. Realizar otro experimento para comprobarlo.

In [53]:
cm

array([180, 178, 154, 202])

In [55]:
np.argmin(cm) #devuelve la posición (índice desde cero) del valor más chico

np.int64(2)

In [56]:
np.argmax(cm) #indice del valor mas grande

np.int64(3)

25. Reproducir estos usos de la funcion np.random.choice() e interpretar que hace.

In [58]:
x = np . array ([" cara ", " ceca "])
s = np . random . choice (x , size =10)
print ("s", s ) #size es desde el uno

y = np . array ([1 ,2 ,3 ,4 ,5 ,6])
t = np . random . choice (y , size =10)
print ("t", t )

u = np . random . choice (y , size =4 , replace = False )
print ("u", u ) #sin repetidos

s [' cara ' ' cara ' ' ceca ' ' ceca ' ' ceca ' ' ceca ' ' cara ' ' ceca '
 ' cara ' ' cara ']
t [4 6 3 1 3 5 2 6 6 1]
u [4 5 3 6]


¿Para que sirve el parametro replace=False? Realicen otras pruebas para verificarlo. Comparen con random.choices y random.sample de la biblioteca estandar de Python.

In [59]:
x = np.array([1, 2, 3])

#RANDOM CHOICE SIN REPETIDOS
np.random.choice(x, size=3, replace=False)

array([3, 2, 1])

In [66]:
import random #para usar random choices y sample
#RANDOM SAMPLE: no adimite repetidos
random.sample(list(x), k=3)

[np.int64(3), np.int64(2), np.int64(1)]

In [64]:
#RANDOM CHOICES: admite repetidos
random.choices(x, k=5)

[np.int64(3), np.int64(3), np.int64(3), np.int64(3), np.int64(1)]