<a href="https://colab.research.google.com/github/smaldonado2004/labo_de_datos/blob/main/clase01_ldd_numpy_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
#son las diferentes librerias que vamos a ocupar en clases

numpy as np → para trabajar con arrays (vectores) y matemáticas

pandas as pd → para trabajar con datos tipo Excel (tablas)

matplotlib.pyplot as plt → para gráficos

seaborn as sns → para gráficos más lindos / estadísticos

👉 El as np, as pd, etc. es solo un alias corto para no escribir nombres largos.

# Python y Jupyter notebook
**Jupyter notebook** permite combinar código Python (celdas Code) con texto con formato y fórmulas matemáticas en Latex (celdas Markdown). Vamos a usar frecuentemente Jupyter notebook en las clases.

Pueden utilizar Jupyter notebook offline desde Anaconda (u otros) o alguna herramienta online, como Google Colab.

Para hacer las prácticas pueden usar Jupyter notebook o cualquier otro entorno.


In [ ]:
# Ejemplo de código
2 + 3 * 5
#sigue el orden de las operaciones matematicas

17

In [ ]:
# Podemos ingresar varias instrucciones en la misma celda
a = 5
a #esto es para imprimir

5

In [ ]:
no_impri = 7 #en este caso no se refleja nd

In [ ]:
# Si ejecutamos varios comandos en una misma celda solo se muestra la última salida
b = 3.14
b
b * 2 #en este caso no se imprime b y luego b*2, sino el valor final

6.28

In [ ]:
# Podemos usar display o print para ver varias salidas
c = "hola"
print(c)
print(a) #toma el valor de a q defini previamente

hola
5


In [ ]:
display(c)

'hola'

### Orden de ejecución
Para ejecutar el contenido de una celta usamos SHIFT+Enter.
Los comandos dentro de la celda se ejecutan en orden.

Si abrimos un Notebook con varias celdas con código, el contenido de esas celdas no se ejecuta hasta que lo hagamos nosotros (podemos hacerlo celda por celda o ejecutar todas automaticamente utilizando "Cell" --> "Run all". (Ejecutar todo en colab).

Ejecutar la primer celda, luego la siguiente y luego nuevamente la primera y ver qué sucede.

In [ ]:
print(z) #al ejecutar 1ro no tiene el valor de la variable z y sale error.

20


In [ ]:
z = 10 + 10

**Pregunta:** ¿Qué son los corchetes que aparecen al lado de cada celda de código?
Es el orden de ejecucion.

Ejecutar la primera celda dos veces y luego la siguiente celda dos veces. ¿Qué sucede en cada caso? ¿Por qué?

In [ ]:
x = 5
x = x * 2
print(x)
#al ejecuar dos veces sale 10 por 5 por 2

10


In [ ]:
x = x * 2
print(x * 5)
#la x que recibo aca es 10, *2 da 20, al ejecutar la 1ra vez sale 100 por 10 por 5
#la 2da vez sale 200. Se queda el valor de 20 * 2 da 40 y por 5 da 200

200


-En la primera celda el valor es constante por definir x=5, en cambio en la segunda celda el valor se va acumulando

**Consejo:** Si entregan código en Jupyter Notebook verifiquen siempre que se pueden ejecutar las celdas en orden de arriba hacia abajo.

### Funciones matemáticas

In [ ]:
a = 5
b = 3.14
a * b # Producto

15.700000000000001

Aparece el resultado exacto? A qué se debe el error?

Es por como se representa en la memoria el resultado de los float, no da un nro exacto.

In [ ]:
print(a**3) # Potencia

125


In [ ]:
print(a % 2) # ¿Qué hace? Es el resto

1


In [ ]:
print(b % 2) # ¿Qué hace? Es el resto de un float

1.1400000000000001


In [ ]:
help('%') #se abre la documentacion que explica como funciona el operador resto

Operator precedence
*******************

The following table summarizes the operator precedence in Python, from
highest precedence (most binding) to lowest precedence (least
binding).  Operators in the same box have the same precedence.  Unless
the syntax is explicitly given, operators are binary.  Operators in
the same box group left to right (except for exponentiation and
conditional expressions, which group from right to left).

Note that comparisons, membership tests, and identity tests, all have
the same precedence and have a left-to-right chaining feature as
described in the Comparisons section.

+-------------------------------------------------+---------------------------------------+
| Operator                                        | Description                           |
|=================================================|=======================================|
| "(expressions...)",  "[expressions...]", "{key: | Binding or parenthesized expression,  |
| value...}", "{expres

In [ ]:
### Tipos de datos
type(a)

int

In [ ]:
type(b)

float

In [ ]:
### Las funciones de Python pueden llamarse con variables de distinto tipo, y se comportan distinto según el tipo de dato
d = 5.0
type(d)

float

In [ ]:
a**100

7888609052210118054117285652827862296732064351090230047702789306640625

In [ ]:
d**100 #ojo en la dif. de elevar un int/float con lo mismo

7.888609052210118e+69

In [ ]:
b**100

4.931338416605635e+49

In [ ]:
c

'hola'

In [ ]:
type(c)

str

In [ ]:
c*2 #repite la palabra dos veces y unida

'holahola'

### Variables booleanas y funciones lógicas
En Python podemos usar variables booleanas True y False, y operadores lógicos: == (igualdad), or, and, not.

In [ ]:
a = True
b = False
print(a == b) #T == F
print(a or b) #T or F
print(a and b) #T anda F
print(a == (not b)) #T == T

False
True
False
True


In [ ]:
not(b)

True

El operador de igualdad aplicado a variables numércias compara solo el valor, no el tipo de dato.

In [ ]:
x1 = 5.0
x2 = 7.0
x3 = 12.0
n1 = 5
print(x1+x2 == x3) #12.0==12.0
print(x1 == 5) #5.0==5 en este caso da TRUE pq AL COMPRAR SOLO INFLUYE EL VALOR NO EL TIPO
print(x1 == n1) #5.0==5 lo mismo que arriba

True
True
True


In [ ]:
type(x1) == type(n1) #en este caso F pq compara el tipo directamente

False

In [ ]:
type(x1) == type(x2)

True

### Listas
Las listas permiten guardar valores de **distintos tipos** en forma ordenada y acceder a
los distintos elementos por su índice, **comenzando desde 0**.

In [ ]:
s = [1, 2, 3.0, "hola", 7 + 3]
s

[1, 2, 3.0, 'hola', 10]

In [ ]:
print(s[0])
print(s[1])
print(s[-1]) # Qué hace esto? Accede al ultimo elemento y HACE EL CALCULO

1
2
10


Podemos indicar también un rango de elementos de la lista.

In [ ]:
s[1:3] # ¿Qué nos devuelve? ¿Por qué?
#Es [inicio incluyente: fin excluyente: paso]

[2, 3.0]

In [ ]:
s[:len(s)] #es lo mismo que s[:5] es el fin (ojo len cuenta desde 1)

[1, 2, 3.0, 'hola', 10]

In [ ]:
s[1:] #aca solo puse el inicio

[2, 3.0, 'hola', 10]

# Numpy

Para trabajar en Python con vectores (y en general para todo tipo de operaciones
matemáticas) vamos a usar el paquete `numpy` . Para eso importamos primero la biblioteca `numpy`
y definimos vectores con el comando `np.array`.

**Vectores.** Los vectores (o arrays) de numpy son similares a las listas, pero **todos los elementos son del mismo tipo (enteros, floats, ...)**

Ejecutar el siguiente código y observar los resultados.

In [ ]:
import numpy as np
v = np.array([1,2,3])
#En el siguiente arreglo de floats el 7 lo toma como 7.0
w = np.array([1.2, 7, np.pi])
#para poder usar pi en numpy ponemos np.pi

print(v)
print(w)
print(v + w) #como un vector: suma componente a componente
#en los res. el 7 en float lo pone como 7.

[1 2 3]
[1.2        7.         3.14159265]
[2.2        9.         6.14159265]


In [ ]:
# El tipo de dato de un array de numpy es ndarray
print(type(v))
print(type(w))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Si queremos saber el tipo de dato de los elementos del array, usamos dtype
print(v.dtype)
print(w.dtype)

int64
float64


### La magia de Numpy.
La biblioteca Numpy reproduce muchas funcionalidades de Matlab (un lugar donde se hacen operaciones matematicas).
La mayoría de las operaciones con vectores de Numpy se hacen **coordenada a coordenada**. Esto permite en muchos casos **evitar usar ciclos o ciclos anidados** y realizarlos con un solo comando.

La diferencia de tiempo de ejecución entre utilizar operaciones apropiadas de Numpy o hacerlo mediante ciclos puede ser muy grande.

Ejecutar los siguientes comandos e interpretar los resultados.

In [ ]:
v = np.array([1,2,np.e,7]) #np.e es el nro. de euler 2,71
w = np.array([1.2, np.pi, 4, 5])

print("v = ", v) #ojo como se conecta info del res con res con coma
print("w = ", w)
print("v + w = ", v + w)

v =  [1.         2.         2.71828183 7.        ]
w =  [1.2        3.14159265 4.         5.        ]
v + w =  [ 2.2         5.14159265  6.71828183 12.        ]


In [ ]:
#todas las operaciones son componente a componente:
print ("v**2 = ", v**2)
print ("v%2 = ", v%2)

v**2 =  [ 1.         4.         7.3890561 49.       ]
v%2 =  [1.         0.         0.71828183 1.        ]


In [ ]:
print ("v > 3?", v > 3)
print ("w < 3.5?", w < 3.5)

v > 3? [False False False  True]
w < 3.5? [ True  True False False]


Algunas funciones de numpy pueden usarse también como métodos

In [ ]:
print(v.sum())
print(np.sum(v)) #ambas opciones dan lo mismo y suman cada componente de v

12.718281828459045
12.718281828459045


Las operaciones lógicas **or y and no se pueden aplicar a vectores**. Debemos usar los símbolos **|
(or)** y **& (and)**.

In [ ]:
print("condicion 1",(v > 3) | (w < 3.5))
#v>3: [False False False  True]
#v<3.5: [True True False  False]
#res: [True  True False  True] O SEA SE APLICA OR ENTRE CADA COMPONENTE

print("condicion 2", (v > 3) & (w < 3.5))
#v > 3: [False False False True]
#v<3.5: [True True False  False]
#res: [False False False  False] SE APLICA Y ENTRE CADA COMPONENTE

condicion 1 [ True  True False  True]
condicion 2 [False False False False]


In [ ]:
print((v > 3) or (w < 3.5))
print((v > 3) and (w < 3.5))
#TIRA ERROR PQ NO SE PUEDE USAR OR Y AND SE USA | &

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Pregunta:** ¿Cómo podemos negar una variable booleana? ¿Como podemos negar un vector de numpy?

In [ ]:
v

array([1.        , 2.        , 2.71828183, 7.        ])

In [ ]:
u = True
#para negar una variable booleana:
u = not u
print(u)

#Sin embargo, en numpy el NOT no funciona, entonces usamos ~
v = np.array([True, True, False, True])
v = ~v
print(v)


False
[False False  True False]


Si queremos quedarnos con sólo algunos elementos de un vector, tenemos varias formas de hacerlo.

In [ ]:
v = np.array([1, 2, np.e, 7, 5])
v[0], v[1], v[-1]  # Dependiendo la versión de Python puede verse distinta la salida

(np.float64(1.0), np.float64(2.0), np.float64(5.0))

In [ ]:
# Print muestra el resultado en forma distinta, más "prolija"
print(v[0], v[1], v[-1])

1.0 2.0 5.0


In [ ]:
v[-2] # Qué nos devuelve esto? El anteultimo valor

np.float64(7.0)

In [ ]:
v[[0, 3]] # Qué nos devuelve esto? LOS VALORES QUE ESTAN EN ESAS POSICIONES (NO ENTRE)

array([1., 7.])

In [ ]:
# Ojo, no podemos hacer lo mismo con listas
s = [1, 2, 3.0, "hola", 7 + 3]
s[[0,3]]

TypeError: list indices must be integers or slices, not list

In [ ]:
# También podemos usar rangos
v[0:3]

array([1.        , 2.        , 2.71828183])

Y podemos seleccionar los elementos que cumplan alguna propiedad.

In [ ]:
v = np.array([1, 2, np.e, 7, 5])
w = np.array([1, 0, 2, 5, 0])
print(w>2) #componente a componente
v[w > 2]
#w > 2: [False False False  True False]
#v[w > 2]: como tengo [1, 2, np.e, 7, 5] y el de la posicion 3 es True, entonces devuelve 7

[False False False  True False]


array([7.])

In [ ]:
v[w>=2]

array([2.71828183, 7.        ])

### Ejercicio
1. Definir un vector $v$ con los números enteros del 0 al 15 (ambos incluidos) utilizando np.arange()
2. A partir de $v$, definir un vector $w$ con los primeros 16 numeros pares (comenzando en 0).
3. A partir de $w$, definir un vector $x$ con los primeros 16 numeros impares (comenzando en 1).
4. Definir un vector $y$ que tenga solo los múltiplo de 3 en $x$.
5. Calcular la suma de los primeros 16 números impares y la suma de los primeros 16 cuadrados perfectos (comenzando en 0)

In [ ]:
v = np.arange(0,16)
print("v: ",v)

v:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
#Para los pares multiplico por dos:
w = v*2
print("w los pares: ",w)

w los pares:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
x = w+1
print("x los impares: ", x)

x los impares:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]


In [ ]:
y = x[x % 3 == 0] #ESTO HACE QUE NOS QUEDEMOS CON LOS X QUE SOLO CUMPLEN LA CONDICION
print("y: multiplos de 3 de x: ",y)

y: multiplos de 3 de x:  [ 3  9 15 21 27]


In [ ]:
print("suma primeros 16 impares: ", x.sum())

cuadrados_perfectos = v**2
print("cuadrados perfectos", cuadrados_perfectos) #solo para comprobar
suma = cuadrados_perfectos.sum()
print(suma)

suma primeros 16 impares:  256
cuadrados perfectos [  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
1240


### **Ejercicio**

1. Evaluar el polinomio $p(x) = x^3 + 3x^2 + 1$ en todas las coordenadas del vector $(-5, -3, -2, 0, 2)$.
2. Graficar estos puntos en el plano, utilizando `plt.scatter(x, y)`
3. Qué pasa si hacemos `plt.plot(x,y)`?
4. Evaluar $p$ en 100 puntos equiespaciados entre $-1$ y $4$ (utilizar `np.linspace` para generar los puntos).


In [ ]:
import matplotlib.pyplot as plt #lo vamos a usar para graficar

#Datos:
x = np.array([-5, -3, -2, 0, 2])
y = x**3 + 3*x**2 + 1 #Ojo como se pone 3x al cuadrado

plt.scatter(x,y)

In [ ]:
# Gráfico de funciones
plt.plot(x,y)

In [ ]:
x = np.linspace(-5,2,100)  # Puntos equiespaciodos
y = ???
plt.plot(x,y)

**Ejercicio.**
Utilizando solo las operaciones y funciones vistas en los ejercicios anteriores, escribir un código
de una sola línea para la función matemática:

$$\langle v, w\rangle = v_1 \cdot w_1 + v_2 \cdot w_2 + \dots + v_n \cdot w_n = \sum_{i=1}^n v_i \cdot w_i$$

In [ ]:
v = np.array([1,0,2,7])
w = np.array([1,2,3,4])

**Matrices.** Las matrices se definen en numpy como arrays de filas. Las operaciones usuales
se realizan coordenada a coordenada al igual que con vectores. Verificar los resultados de los
siguientes comandos.

In [ ]:
A = np.array([[3, 2, 2], [-1, 0, 1], [-2, 2, 5]])
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
C = np.array([[0, 1, -1], [5, -2, 1]])
A + B

In [ ]:
A

In [ ]:
print(B)

In [ ]:
A * B

In [ ]:
C**2

El producto usual de matrices se realiza con el comando @ .

A.T es la transpuesta de A.

Verificar los resultados de los siguientes comandos.

In [ ]:
C>2

In [ ]:
A @ B

In [ ]:
B @ C

In [ ]:
B.shape, C.shape

In [ ]:
B @ C.T

**Ejercicio**

Evaluar el polinomio $p(x) = x^3 + 3x^2 + 1$ en todas las coordenadas de la matriz
$$
\begin{pmatrix}
0 & -1 & -2 \\
-2 & 3 & 1
\end{pmatrix}
$$


## Funciones

Las funciones son bloques de código organizado que se usan para realizar tares específicas.

Reciben un input (un número o una variable, por ejemplo) y devuelven un output. Los inputs van
entre paréntesis y separados por una coma, si hay más de uno.

Muchas funciones están disponibles en la biblioteca estándar de Python, otras estás agrupadas en distintas bibliotecas, como numpy que agrupa una gran cantidad de funciones matemáticas.

El objetivo de estos ejercicios es familiarizarse con varias funciones básicas de Python.

Ejecutar estas operaciones en la consola para entender qué hacen las funciones de numpy.

In [ ]:
a = np.sqrt(2)
a

In [ ]:
np.round(a)

In [ ]:
np.round(a, 2)

In [ ]:
help(np.round)

In [ ]:
# Para las funciones de numpy, también podemos ver información con np.info
np.info(np.round)

Muchas funciones de numpy se pueden aplicar también en arrays.

In [ ]:
a = np.sqrt(2)
v = np.array([a, a**2, a**3, a**(.5)])
v

In [ ]:
np.floor(v)

**Ejercicio:** Explorar las funciones np.max() , np.min() , np.mean() y np.sort() aplicadas al vector
v del ejercicio anterior. ¿Qué hace cada una?

En Python podemos definir nuestras propias funciones utilizando `def`.

¿Qué hace la siguiente función?

¿Qué resultados esperan al aplicar la función a los vectores $v_0$ y $v_1$?

In [ ]:
def positivo(v):
    return np.all(v > 0)

v0 = np.array([3, 4])
v1 = np.array([3, 5, -1, 1])

In [ ]:
print(positivo(v0))

In [ ]:
positivos(v1)

In [ ]:
v1 > 0

**Ejercicio.** Definir una función que calcule la norma-2 de un vector y verificarla en los vectores $v_0$ y $v_1$ del ejercicio anterior.

## Azar y simulaciones

Reproducir estos usos de la función np.random.choice() e interpretar qué hace.

In [ ]:
x = np.array(["cara", "ceca"])
np.random.choice(x, size=10)

In [ ]:
y = np.array([1,2,3,4,5,6])
np.random.choice(y, size=10)

In [ ]:
np.random.choice(y, size=4, replace=False)

In [ ]:
# Funcionará?
np.random.choice(y, size=10, replace=False)

**Ley de los grandes números.** Esta ley asegura que si tiramos $n$ veces una moneda, el promedio de veces que sale cara tiende a $1/2$ cuando $n$ tiende a infinito.

Simular 10 lanzamientos de una moneda y calcular el promedio de veces que sale cara. Repetir para $n = 1000$ y $n = 100.000$.

In [ ]:
n = 10
x = np.array(["cara", "ceca"])
tiradas = np.random.choice(x, size=n)
tiradas

In [ ]:
np.sum(tiradas=="cara") / n

**Ejercicio.** Se tira $n$ veces una moneda. Intentar predecir, si existen, los siguientes límites cuando $n$ tiene a infinito y verificar la intuición mediante simulaciones.

1. La cantidad de caras dividido por la cantidad de cecas.
2. La cantidad de caras menos la cantidad de cecas
3. La cantidad de caras menos la cantidad de cecas, divido por la cantidad total de tiradas.
4. **(Difícil)** Considerando las veces que salieron tres caras seguidas, el promedio de veces que en la siguiente tirada sale nuevamente cara.


**Ejercicio.**
1. Generar 1000 puntos al azar en el cuadrado de vértices $(0,0), (0,1), (1,0), (1,1)$ y calcular que proporción esta a distancia menor de 1 del origen $(0,0)$.
2. Utilizar el resultado anterior para dar una aproximación de $\pi$.
